[package]
name = "chip8-rs"
version = "0.1.0"
authors = ["Taylor Denouden <taylordenouden@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
sdl2 = "0.34.3"